name: TypeCheck

on: 
  pull_request:
    branches: [ main ]
    paths :
    - '**.tsx'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  
    
    steps:

      - uses: actions/checkout@v2
      
      - name: Setup dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install nodejs
      
      - name: Install API
        run: npm install --no-optional

      - name: Run typechecker
        run: npx tsc 